name: DEPLOY

on:
  push:
    tags:
      - '*'

jobs:
  Deploy_To_Cocoapods:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        set -eo pipefail
        export BUMP_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings

